version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: we-read-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: we-read-tool
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: we-read-backend
    restart: unless-stopped
    ports:
      - "7001:7001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/we-read-tool
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: we-read-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:7001
    depends_on:
      - backend

volumes:
  mongodb_data: 
 